#pragma once

#include "../platform.h"

#ifndef FEATURE_ESTD_IOS_GCOUNT
#define FEATURE_ESTD_IOS_GCOUNT 1
#endif

#ifndef FEATURE_ESTD_AGGRESIVE_BITFIELD
#define FEATURE_ESTD_AGGRESIVE_BITFIELD 1
#endif


#ifndef FEATURE_ESTD_OSTREAM_SETW
#define FEATURE_ESTD_OSTREAM_SETW 1
#define FEATURE_ESTD_OSTREAM_SETFILL 1
#define FEATURE_ESTD_OSTREAM_SETIOSALIGN 1
#endif

#ifndef FEATURE_ESTD_OSTREAM_OCTAL
#define FEATURE_ESTD_OSTREAM_OCTAL 1
#endif


