#pragma once

// VDK.h is autogenerated from VisualDSP into your project folder
#include <VDK.h>

#ifndef _ADI_THREADS
#error Is VDK active and -thread option specified?
#endif

namespace estd {

class mutex
{
    VDK::MutexID mutex_id;

public:
    mutex()
    {
        mutex_id = VDK::CreateMutex();
    }

    ~mutex()
    {
    	if (mutex_id != UINT_MAX)
            VDK::DestroyMutex(mutex_id);
    }

    void lock()
    {
        VDK::AcquireMutex(mutex_id);
    }

    void unlock()
    {
        VDK::ReleaseMutex(mutex_id);
    }
};

}