#pragma once

// This file is auto-populated from git-version.in.h via CMake + Python
// Generated at ${TIMESTAMP_ISO8601}

#include <estd/port/arch/version.h>

#define ${PROJECT_NAME_UPPER}_GIT_SEMVER_MAJOR  ${GIT_TAG_SEMVER_MAJOR}
#define ${PROJECT_NAME_UPPER}_GIT_SEMVER_MINOR  ${GIT_TAG_SEMVER_MINOR}
#define ${PROJECT_NAME_UPPER}_GIT_SEMVER_PATCH  ${GIT_TAG_SEMVER_PATCH}
#define ${PROJECT_NAME_UPPER}_GIT_SEMVER_SUFFIX "${GIT_TAG_SEMVER_PRERELEASE}"
#define ${PROJECT_NAME_UPPER}_GIT_SEMVER_ID     "${GIT_TAG_SEMVER_IDENTIFIER}"

#define ${PROJECT_NAME_UPPER}_GIT_VERSION  ESTD_BUILD_SEMVER(${GIT_TAG_SEMVER_MAJOR}, ${GIT_TAG_SEMVER_MINOR}, ${GIT_TAG_SEMVER_PATCH})
#define ${PROJECT_NAME_UPPER}_GIT_DESCRIBE "${GIT_DESCRIBED}"
