#pragma once

// This file is auto-populated from version.in.h via CMake

#include <estd/port/arch/version.h>

#define ${PROJECT_NAME_UPPER}_GIT_SEMVER_MAJOR  ${GIT_TAG_SEMVER_MAJOR}
#define ${PROJECT_NAME_UPPER}_GIT_SEMVER_MINOR  ${GIT_TAG_SEMVER_MINOR}
#define ${PROJECT_NAME_UPPER}_GIT_SEMVER_PATCH  ${GIT_TAG_SEMVER_PATCH}
#define ${PROJECT_NAME_UPPER}_GIT_SEMVER_SUFFIX "${GIT_TAG_SEMVER_SUFFIX}"
#define ${PROJECT_NAME_UPPER}_GIT_SEMVER_ID     "${GIT_TAG_SEMVER_ID}"

#define ${PROJECT_NAME_UPPER}_GIT_VERSION  ESTD_BUILD_SEMVER(${GIT_TAG_SEMVER_MAJOR}, ${GIT_TAG_SEMVER_MINOR}, ${GIT_TAG_SEMVER_PATCH})
#define ${PROJECT_NAME_UPPER}_GIT_DESCRIBE "${GIT_DESCRIBED}"
