#pragma once

// This file is auto-populated from version.in.h via CMake

#include <estd/port/arch/version.h>

#define ${PROJECT_NAME_UPPER}_VER_MAJOR     ${PROJECT_VERSION_MAJOR}
#define ${PROJECT_NAME_UPPER}_VER_MINOR     ${PROJECT_VERSION_MINOR}
#define ${PROJECT_NAME_UPPER}_VER_PATCH     ${PROJECT_VERSION_PATCH}

#define ${PROJECT_NAME_UPPER}_VERSION  ESTD_BUILD_SEMVER(${PROJECT_VERSION_MAJOR}, ${PROJECT_VERSION_MINOR}, ${PROJECT_VERSION_PATCH})
#define ${PROJECT_NAME_UPPER}_VERSION_STR "${PROJECT_VERSION}"
