#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := basic

EXTRA_CPPFLAGS := -DESP32

#include main/test.mk
include version_finder.mk

include $(IDF_PATH)/make/project.mk