# Exposes 'python' folder as consumable tools for other repos

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "build-tooling"
version = "0.1.0"
requires-python = ">=3.10"
description = "estd semver and git helpers"

[tool.setuptools.packages.find]
where = ["python"]
include = ["*"]

[tool.setuptools]
# A little fiddly because toml wants a root/package structure (reasonable)
# but we have python/*.py
py-modules = ["semver", "git-describe-to-header"]