name: CMake

on:
  push:
    branches: [ "feat/**", "alpha" ]

jobs:
  select-profile:
    runs-on: ubuntu-slim
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}

    steps:
    - uses: actions/checkout@v6
    - id: matrix
      working-directory: tools/github
      run: ./get-matrix cmake ${GITHUB_REF_NAME} >> "$GITHUB_OUTPUT"

  build:
    needs: select-profile
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.select-profile.outputs.matrix) }}

    env:
      CC: ${{ matrix.compiler }}
      CXX: ${{ matrix.compiler == 'gcc' && 'g++' || 'clang++' }}
      CPM_SOURCE_CACHE: ~/.cache/cpm

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
        # Reach deep enough to grab latest tags
        fetch-depth: 1000
        fetch-tags: true

    - uses: actions/cache@v5
      with:
        path: ${{ env.CPM_SOURCE_CACHE }}
        key: ${{ runner.os }}-cpm-${{ hashFiles('CMakeLists.txt') }}

    - id: cmake-build
      uses: threeal/cmake-action@v2.1.0
      with:
        source-dir: ${{github.workspace}}/test/catch
        options: |
          CMAKE_CXX_STANDARD=${{ matrix.cxx_std }}
          CMAKE_CXX_STANDARD_REQUIRED=ON
          CMAKE_BUILD_TYPE=${{ matrix.build_type }}

      # TODO: -DCMAKE_CXX_EXTENSIONS=OFF

    - name: Test
      uses: threeal/ctest-action@v1.1.0
      with:
        test-dir: ${{ steps.cmake-build.outputs.build-dir }}

