name: CMake

on:
  push:
    branches: [ "feat/**", "alpha" ]

jobs:
  select-profile:
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}

    steps:
    - uses: actions/checkout@v6
    - id: matrix
      shell: bash
      working-directory: tools/github
      run: ./get-matrix cmake ${GITHUB_REF_NAME} >> "$GITHUB_OUTPUT"

  build:
    needs: select-profile
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.select-profile.outputs.matrix) }}

    env:
      unit_test_dir: ${{github.workspace}}/test/catch
      CC: ${{ matrix.compiler }}
      CXX: ${{ matrix.compiler == 'gcc' && 'g++' || 'clang++' }}

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Build
      uses: threeal/cmake-action@v2.1.0
      with:
        source-dir: ${{env.unit_test_dir}}
        options: |
          CMAKE_CXX_STANDARD=${{ matrix.cxx_std }}
          CMAKE_CXX_STANDARD_REQUIRED=ON
          CMAKE_BUILD_TYPE=${{ matrix.build_type }}

      # TODO: -DCMAKE_CXX_EXTENSIONS=OFF

    - name: Test
      uses: threeal/ctest-action@v1.1.0
      with:
        # DEBT: Grab "build-dir" from above cmake-action
        test-dir: ${{env.unit_test_dir}}/build

