name: ESP-IDF

on:
  push:
    branches: [ "feat/**", "alpha" ]

jobs:
  select-profile:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}

    steps:
    - uses: actions/checkout@v6
    - id: matrix
      shell: bash
      working-directory: tools/github
      run: ./get-matrix esp-idf ${GITHUB_REF_NAME} >> "$GITHUB_OUTPUT"

  build:
    needs: select-profile
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.select-profile.outputs.matrix) }}
        #version: [v5.3.5, v5.4.4, v5.5.4, v6.0]
        #target: [esp32, esp32s3, esp32c6]
      exclude:
      - version: v5.3.5
        target: esp32c5
    steps:
    - name: Checkout repo
      uses: actions/checkout@v6
    - name: esp-idf QEMU option prep
      if: |
        matrix.version == 'v6.0.1' &&
          (matrix.target == 'esp32' ||
          matrix.target == 'esp32c3' ||
          matrix.target == 'esp32s3')
      run: |
        cat >> $GITHUB_ENV <<EOF
        BUILD_OPT="-DSDKCONFIG_DEFAULTS=sdkconfig.defaults.ci;sdkconfig.defaults"
        ENABLE_QEMU=true
        EOF
    - name: "esp-idf build"
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: ${{ matrix.version }}
        target: ${{ matrix.target }}
        path: 'test/esp-idf/unity'
        #command: "idf.py build ${BUILD_OPT}"
        command: "idf.py build ${{ env.BUILD_OPT }}"
    # 27APR26 MB TODO: Rework this to be a needs: relationship
    - name: "esp-idf qemu"
      timeout-minutes: 1
      if: env.ENABLE_QEMU=='true'
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: ${{ matrix.version }}
        target: ${{ matrix.target }}
        path: 'test/esp-idf/unity'
        command: idf.py qemu --qemu-extra-args="-no-reboot" | tee qemu_output.txt
    - name: "QEMU output inspection"
      if: env.ENABLE_QEMU=='true'
      # 29APR26 MB: Almost there.  Python looks to be parsing well, just doing nothing
      # with it.
      run: cat test/esp-idf/unity/qemu_output.txt | tools/esp-idf/unity-gh-action.py
