name: ESP-IDF

on:
  push:
    branches: [ "dev/**", "alpha" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        version: [v5.2.3, v5.3.2, v5.4-beta2]
        target: [esp32, esp32c3, esp32c6, esp32s3]

    steps:
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: ${{ matrix.target }}
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: ${{ matrix.version }}
        target: ${{ matrix.target }}
        path: 'test/rtos/esp32/unity'

  build-p4:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: ESP32P4
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.3.2
        target: esp32p4
        path: 'test/rtos/esp32/unity'

  build-beta:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: ESP32c5
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.4-beta2
        target: esp32c5
        path: 'test/rtos/esp32/unity'
