#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := ios

EXTRA_CPPFLAGS := -DESP32

include ../../template/version_finder.mk

include $(IDF_PATH)/make/project.mk
