#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := chrono

include version_finder.mk

include $(IDF_PATH)/make/project.mk
